name: new_wave_round_one
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  retrofit: ^4.0.1
  dio: ^5.0.3
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
